#!/usr/bin/env bash
# Kick off LoRA training on RunPod using sd-scripts.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SD_SCRIPTS_DIR="${SD_SCRIPTS_DIR:-/workspace/sd-scripts}"
CONFIG_FILE="${CONFIG_FILE:-${SCRIPT_DIR}/config.toml}"
ACCELERATE_CMD="${ACCELERATE_CMD:-accelerate launch}"
MIXED_PRECISION="${MIXED_PRECISION:-bf16}"  # set MIXED_PRECISION=fp16 for non-bf16 GPUs

PROJECT_ROOT="${PROJECT_ROOT:-/workspace/project}"
MODEL_SRC_DEFAULT="${MODEL_SRC_DEFAULT:-${PROJECT_ROOT}/yokai-gen/models/base/sd_xl_base_1.0.safetensors}"
DATASET_SRC_DEFAULT="${DATASET_SRC_DEFAULT:-${PROJECT_ROOT}/yokai-gen/Preprocessing/LoRA-making/prepared-dataset}"
MODEL_TARGET="${MODEL_TARGET:-/workspace/models/sd_xl_base_1.0.safetensors}"
DATASET_TARGET="${DATASET_TARGET:-/workspace/datasets/yokai/train}"
ACCELERATE_CONFIG_FILE="${ACCELERATE_CONFIG_FILE:-/workspace/.cache/huggingface/accelerate/default_config.yaml}"

mkdir -p "$(dirname "${MODEL_TARGET}")" "$(dirname "${DATASET_TARGET}")" "$(dirname "${ACCELERATE_CONFIG_FILE}")"

# Auto-wire model/data if they exist in the checked-out project tree.
if [ ! -f "${MODEL_TARGET}" ] && [ -f "${MODEL_SRC_DEFAULT}" ]; then
  ln -sf "${MODEL_SRC_DEFAULT}" "${MODEL_TARGET}"
fi
if [ ! -d "${DATASET_TARGET}" ] && [ -d "${DATASET_SRC_DEFAULT}" ]; then
  ln -s "${DATASET_SRC_DEFAULT}" "${DATASET_TARGET}"
fi

# Ensure accelerate has a non-interactive config (generated by setup.sh).
if [ ! -f "${ACCELERATE_CONFIG_FILE}" ]; then
  cat > "${ACCELERATE_CONFIG_FILE}" <<'YAML'
compute_environment: LOCAL_MACHINE
distributed_type: NO
num_processes: 1
machine_rank: 0
num_machines: 1
mixed_precision: bf16
use_cpu: false
downcast_bf16: no
YAML
fi
export ACCELERATE_CONFIG_FILE

if [ ! -d "${SD_SCRIPTS_DIR}" ]; then
  echo "[train] sd-scripts not found at ${SD_SCRIPTS_DIR}" >&2
  exit 1
fi
if [ ! -f "${CONFIG_FILE}" ]; then
  echo "[train] Config file not found at ${CONFIG_FILE}" >&2
  exit 1
fi

cd "${SD_SCRIPTS_DIR}"

${ACCELERATE_CMD} --num_processes=1 --mixed_precision="${MIXED_PRECISION}" \
  train_network.py --config_file "${CONFIG_FILE}"

